Update Readme. Stop using Git Tags (doesn't work with squash/merge).
RamseyInHouse/frontend pull request #18
Opened 2020-12-11 22:59 UTC by ChristianJHughes

2020-12-15 21:49 UTC, alexmacarthur requested changes
Nice work! Everything reads great -- just a couple of small things.

2020-12-15 21:49 UTC, alexmacarthur commented on README.md
> +1. Open a feature branch for your release
```suggestion
1. Open a feature branch for your release.
```

2020-12-15 21:49 UTC, alexmacarthur commented on README.md
> +Packages are published to NPM within the [`ramseyinhouse`](https://www.npmjs.com/org/ramseyinhouse) organization.
I think the appropriate way to refer to it is `npm`, even in written copy. It's this way in their [own copy](https://www.npmjs.com/get-npm), as well as external sources like [Wikipedia](https://en.wikipedia.org/wiki/Npm_(software)).

```suggestion
Packages are published to npm within the [`ramseyinhouse`](https://www.npmjs.com/org/ramseyinhouse) organization.
```

2020-12-15 21:49 UTC, alexmacarthur commented on README.md
> +Package versions are automatically published to [NPM](https://www.npmjs.com/org/ramseyinhouse) via [Github Actions](./.github/workflows/main.yml) as they are updated.
```suggestion
Package versions are automatically published to [npm](https://www.npmjs.com/org/ramseyinhouse) via [Github Actions](./.github/workflows/main.yml) as they are updated.
```

2020-12-15 21:49 UTC, alexmacarthur commented on README.md
> +Once ready for publication to NPM:
```suggestion
Once ready for publication to npm:
```

2020-12-15 21:49 UTC, alexmacarthur commented on README.md
> +3. Open a pull request. Once merged, the new package version(s) will be published to NPM automatically.
```suggestion
3. Open a pull request. Once merged, the new package version(s) will be published to npm automatically.
```

2020-12-15 22:08 UTC, ChristianJHughes commented
@alexmacarthur Thank you, updates made! Could you take another look?

2020-12-16 01:30 UTC, alexmacarthur approved these changes
🚀

2020-12-16 16:11 UTC, merged